services:
  - type: web
    name: dinadvent_web_test
    env: node
    region: frankfurt
    plan: starter
    buildCommand: yarn; blitz db migrate; blitz build
    startCommand: blitz start --production -H 0.0.0.0
    healthCheckPath: /api/healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dinadvent_db_test
          property: connectionString
  # - type: web
  #   name: dinadvent_web_prod
  #   env: node
  #   region: frankfurt
  #   plan: starter
  #   buildCommand: yarn; blitz db migrate; blitz build
  #   startCommand: blitz start --production -H 0.0.0.0
  #   healthCheckPath: /api/healthcheck
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: dinadvent_db_prod
  #         property: connectionString
databases:
  - name: dinadvent_db_test
    region: frankfurt
    plan: starter
    ipAllowList: []
  # - name: dinadvent_db_prod
  #   region: frankfurt
  #   plan: starter
  #   ipAllowList: []
