name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm start
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: start server
        uses:
      - name: Cypress run
        uses: cypress-io/github-action@v2
