name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Use Node.js 12.x"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn migrate
      - run: yarn build
      - run: yarn test:ci
